config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users
  root to: "activities#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")

  resources :news, only: [:index, :show]
  resources :activities, only: [:index, :show] do
    resources :participations, only: [:create]
    resources :reviews, only: [:create]
      end

  get "my_dashboard", to: "participations#my_dashboard"
  resources :participations, only: [:destroy]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_one :chatroom
  has_many_attached :photos
  has_many :reviews, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  has_many :participations

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 40 }
  validates :capacity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  # validates :price, presence: true, numericality: { greater_than: 0 }
  # validates :location, presence: true
  # validates :photo, presence: true
  validates :category, presence: true

  def average_rating
    total = 0
    self.reviews.each do |review|
      total += review.rating.to_i
    end
    total / self.reviews.count
  rescue ZeroDivisionError
    0.0
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  belongs_to :activity
  has_many   :messages
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :chatroom

  def sender?(a_user)
    user.id == a_user.id
  end
end

app/models/news.rb
class News < ApplicationRecord
  has_one_attached :photo
end

app/models/participation.rb
class Participation < ApplicationRecord
  belongs_to :activity
  belongs_to :user
  validate :participation_date_within_dates


  private

  def participation_date_within_dates
    errors.add(:participation_date, "Must be between start and end date") unless (activity.start_date...activity.end_date).include?(participation_date)
  end


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :activity
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :participations
  has_many :reviews
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :avatar
  belongs_to :entity, optional: true
  validate :user_can_participate_in_only_one_entity

  validates :username, presence: true, uniqueness: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  def user_can_participate_in_only_one_entity
    puts "coucou"
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  skip_before_action :authenticate_user!

  def index

    @activities = Activity.all

    if params[:query].present?
      sql_subquery = "location ILIKE :query OR address ILIKE :query OR category ILIKE :query"
      @activities = @activities.where(sql_subquery, query: "%#{params[:query]}%")
    end

    if params[:where].present? && params[:where] != "all"
      @activities = @activities.where(location: params[:where])
    end

    @markers = @activities.geocoded.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { activity: activity })
      }
    end
  end

  def show
    @participation = Participation.new
    @activity = Activity.find(params[:id])
    @review = Review.new
    @markers = [
      {
        lat: @activity.latitude,
        lng: @activity.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { activity: @activity })
      }
    ]
    # @average = @activity.review
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :avatar])
  end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
before_action :authenticate_user!
  def show
    @chatroom = Chatroom.find(params[:id])
    @message = Message.new
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @chatroom = Chatroom.find(params[:chatroom_id])
    @message = Message.new(message_params)
    @message.chatroom = @chatroom
    @message.user = current_user
    if @message.save
      ChatroomChannel.broadcast_to(
        @chatroom,
        message: render_to_string(partial: "message", locals: { message: @message }),
        sender_id: @message.user.id
      )
      head :ok
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController

  def index
    @news = News.all

    if params[:query].present?
      @news = @news.where(theme: params[:query])
    end


    if params[:where].present? && params[:where] != "all"
      @news = @news.where(theme: params[:where])
    end

  end

  def show
  end
end

app/controllers/participations_controller.rb
class ParticipationsController < ApplicationController

  def create
    @participation = Participation.new(participation_params)
    @activity = Activity.find(params[:activity_id])
    @participation.activity = @activity
    @participation.user = current_user
    @review = Review.new

    if @participation.save

      redirect_to my_dashboard_path, notice: 'Participation was successfully created.'
    else
      flash[:alert] = @participation.errors.messages[:participation_date]
      render 'activities/show', status: :unprocessable_entity
    end
  end

  def my_dashboard
    @participations = Participation.where(user: current_user)
    @activities = @participations.map{ |participation| participation.activity}
  end

  def destroy
    @participation = Participation.find_by(id: params[:id])
    if @participation.destroy
      redirect_to my_dashboard_path, notice: 'Participation was successfully cancelled.'
    end
  end

  private

  def participation_params
    params.require(:participation).permit(:participation_date)
  end


end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @activity = Activity.find(params[:activity_id])
    @review.activity = @activity
    @review.user = current_user
    if @review.save
      redirect_to activity_path(@activity)
    else
      flash[:alert] = "Something went wrong."
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/activities/_info_window.html.erb
<%= link_to activity_path(activity) do %>
  <div class="pins">
    <h2><%= activity.name %></h2>
    <p><%= activity.address %></p>
    <%= cl_image_tag activity.photos.first.key, width: 100, height: 75, crop: :fill%>
  </div>
<% end %>

app/views/activities/index.html.erb
<%# <div><%= render "shared/search" %>
<%= render "shared/navbar" %>

<div class="cards-container" id="toppage">
  <div class="cards">
      <% @activities.each do |activity| %>
        <%= link_to activity_path(activity) do %>
          <div class= "card-category">
            <%= cl_image_tag activity.photos.first.key, width: 350, height: 150, crop: :fill%><hr>
            <h1><%= activity.name %></h1>
            <p class="location"><%= activity.location %></p>
            <ul>
              <% if activity.category == "indoor" %>
                <li class="indoor"><%= activity.category %></li>
              <% else %>
                <li class="outdoor"><%= activity.category %></li>
                </li>
              <% end %>
              <div class= "list">
                <div class="price">
                <% if activity.price == 0 %>
                <li style="text-align: right; color: green;"><%= "free" %></li>
                <% else %>
                <li style="text-align: right;"><%= activity.price %></li>
                <% end %>
                <p style="font-size: 23px; color: grey;">euros</p>
                </div>
                <div class="capacity" style="margin-left: 75px">
              <li><%= activity.capacity - activity.participations.size %></li>
                <p style="font-size: 23px; color: grey;">Spots left</p>
                </div>
              </div>
              <hr>
              <li class="text"><%= activity.description[0..115]%>...</li>
            </ul>
            </div>
        <% end %>
      <% end %>
  </div>
    <div class="map" style="width: 50%; height: 100vh;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

app/views/activities/show.html.erb
<% if user_signed_in? %>
  <%= render "shared/topnavbar" %>
<% end %>
<!------ Include the above in your HEAD tag ---------->
<div id="totalcontainer" data-controller="toggle-map">
<div id="containershow">
  <div>
    <div>
    <div><p style="font-size: 30px;"><%= (' ⭐ ' * @activity.average_rating)  %><%= @activity.average_rating %>/5
      <%if @activity.average_rating >= 4 %> <i class="fa-solid fa-trophy fa-2xs" style="color: #3b2747;"></i><span style="color:#f2ad73;"><%= "    Top rated activity" %></span>
      <% end %></p>
    </div> <hr style="width: 50%; border-top: 1px solid black;">
      <div class="card-show text-center">
      <div id="carouselExample" class="carousel slide">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <%= cl_image_tag @activity.photos[0].key , width: 900, height: 500%>
          </div>
          <div class="carousel-item">
            <%= cl_image_tag @activity.photos[1].key, width: 900, height: 500%>
          </div>
          <div class="carousel-item">
            <%= cl_image_tag @activity.photos[2].key, width: 900, height: 500%>
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExample" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExample" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">Next</span>
        </button>
      </div>

        <div class="card-body">
          <h5 class="card-title"><%= @activity.name %></h5>
          <hr>
          <p>
             <%# <button class="btnmap" data-toggle="collapse" > %>

            <button class="btnmap" data-toggle="collapse" href="" role="button" aria-expanded="false" aria-controls="collapseExample" data-action="click -> toggle-map#maptoggle" >
              <i class="fa-solid fa-map fa-lg" style="color: #f2ad73;"></i> Maps
            </button>
          </p>
          <div class="collapse" id="collapseExample">
            <div class="card-show card-body">
              <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d11880.492291371422!2d12.4922309!3d41.8902102!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x28f1c82e908503c4!2sColosseo!5e0!3m2!1sit!2sit!4v1524815927977" width="100%" height="200" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
          </div>
        </div>
        <div class="card-footer text-muted">
          <div class="row">

          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="moreinfos">
    <h1><%= @activity.name %><hr></h1>
    <i class="fa-solid fa-play" style="color: #472151;"></i> <%= @activity.description %><hr>
    <i class="fa-solid fa-location-pin" style="color: #f2ad73;"></i>  <%= @activity.address %> <hr>

  <div class="d-none" data-toggle-map-target="map">
      <div class="mapshow" style="width: 400px; height: 250px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div><hr>
  </div>

<%# ------------- More infos ------------- %>
    <%# <i class="fa-solid fa-person-breastfeeding" style="color: #f2ad73;"></i> <%= @activity.capacity - @activity.participations.size Spots <hr> %>
    <i class="fa-solid fa-hand-holding-dollar" style="color: #f2ad73;"></i> <%= @activity.price%> € | Mum    <i class="fa-solid fa-children" style="color: #f2ad73;"></i>   <strong>Children Free</strong><hr>

<%# ------------- Participation button : calender ------------- %>
    <i class='fas fa-calendar-alt'style="color: #f2ad73;"></i> <%= @activity.start_date%> - <%= @activity.end_date%>
<div class="col" style="margin: 20px;">
               <%= simple_form_for [@activity, @participation], data: { controller: 'flatpickr' } do |f| %>
               <%= f.date_field :participation_date, as: :date_field, input_html: { data: { flatpickr_target: "participtationDate" } } %>
               <span class="confirm"><%= f.submit 'Confirm Date' %></span>
               <% end %></div> <hr>
<%# ------------- Reviews ------------- %>
<% if Participation.where(user: current_user, activity: @activity).any? %>
  <p><i class="fa-solid fa-star fa-sm" style="color: #f2ad73;"></i> <%= simple_form_for([@activity, @review], data: { controller: "form-submit" }) do |f|%></p>
      <%= f.input :rating, collection: (1..5).to_a, label: "Add a rating", input_html: {data: { controller: "star-rating", action: "click->form-submit#submit"} }  %>
          <%= f.submit %>
      <% end %><hr>
      <% end %>
    <%# <i class="fa-solid fa-hand-holding-dollar" style="color: #f2ad73;"></i> <%= @activity.participations.size %>
    <i class="fa-solid fa-link" style="color: #f2ad73;"></i> <%=link_to "Read more about it", @activity.link,  target: "_blank" %> <hr>

  </div>
</div>

</div>

app/views/chatrooms/show.html.erb
<%= render "shared/topnavbar" %>

<div id="chatroom_container" class="container chatroom" data-controller="chatroom-subscription" data-chatroom-subscription-chatroom-id-value="<%= @chatroom.id %>"    data-chatroom-subscription-current-user-id-value="<%= current_user.id %>">

  <h2 class="icon_chatroom"><i class="fa-solid fa-comment-dots" style="color: #ffa345;"></i></h2>
  <h1 class="title_chatroom"><%= @chatroom.name + " Team"%></h1>

    <div class="messages" data-chatroom-subscription-target="messages">
      <% @chatroom.messages.each do |message| %>

        <div class="message-row d-flex <%= message.sender?(current_user) ? 'justify-content-end' : 'justify-content-start' %>">
          <div class="<%= message.sender?(current_user) ? 'sender-style' : 'receiver-style' %>">
            <%= render "messages/message", message: message %>
          </div>
        </div>

      <% end %>
    </div>

    <%= simple_form_for [@chatroom, @message], html: { class: "d-flex custom-form", data: { action: "turbo:submit-end->chatroom-subscription#resetForm" } } do |f| %>
      <%= f.input :content,
                 label: false,
                 placeholder: "Message ##{@chatroom.name} team",
                 wrapper_html: {class: "flex-grow-1"} %>
      <%= f.submit "Send", class: "btn btn-primary mb-3", id: "btn-input"%>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Newmums</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=ADLaM+Display&family=Amatic+SC&family=Assistant:wght@500&family=Cardo&family=Cormorant+Garamond:wght@300&family=Figtree:wght@500&family=Montserrat:wght@200;300;400;500;600&family=Open+Sans:wght@300&family=Raleway:wght@300;400&family=Work+Sans:wght@100&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://ga.jspm.io/npm:star-rating.js@4.3.0/dist/star-rating.css">
    <meta name="turbo-visit-control" content="reload">
  </head>

  <body>
    <%# <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <%= render "shared/flashes" %>
    <%= yield %>
  <div class="footer">
    <div class="footer-links">
      <a href="https://github.com/Hasnaes/newmums" target="blank"><i class="fab fa-github"></i></a>
      <a href="https://www.instagram.com/explore/tags/newmum/" target="blank" ><i class="fab fa-instagram"></i></a>
      <a href="https://www.facebook.com/newgenmum/" target="blank"><i class="fab fa-facebook"></i></a>
    </div>
    <div class="footer-copyright">
      NewMum with <i class="fas fa-heart"></i>
    </div>
  </div>
  </body>

</html>

app/views/messages/_message.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.username %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/messages/_messages.html.erb
<div id="message-<%= message.id %>">
  <small>
    <strong><%= message.user.username %></strong>
    <i><%= message.created_at.strftime("%a %b %e at %l:%M %p") %></i>
  </small>
  <p><%= message.content %></p>
</div>

app/views/news/index.html.erb
<%= render "shared/topnavbar" %>
<div class="all_tips">
  <div class="container" id="themes_color">
    <div id="themes" class= "d-flex">
      <div class="education">
        <%= link_to params: {where: "Education"}, method: :get do %>
        <%= image_tag "education.avif", width: 400, height: 350, crop: :fill %>
        <p class="link-education">EDUCATION</p>
        <% end %>
      </div>
      <div class="education">
        <%= link_to "Products", params: {where: "Products"}, method: :get do %>
        <%= image_tag "allproduct.webp", width: 400, height: 350, crop: :fill %>
        <p class="link-education">PRODUCTS</p>
        <% end %>
      </div>
      <div class="education">
        <%= link_to "Feeding", params: {where: "Feeding"}, method: :get do %>
        <%= image_tag "feeding.png", width: 400, height: 350, crop: :fill %>
        <p class="link-education">FEEDING</p>
        <% end %>
      </div>

    </div>
      <div class="link_tips"><%= link_to "SEE ALL TIPS & TRICKS", news_index_path %></div>
  </div>


  <div class="card-container-news">
    <% @news.each do |news| %>
      <div class="card-product-news">
        <%= cl_image_tag news.photo.key, width: 150, height: 150, crop: :fill%>
        <div class="card-product-infos-news">
          <h3 style="color: #66adab;"><%= news.author %> | <%= news.date %></h3>
          <h2><%= news.title %></h2>
          <p><%= news.description %></p>
          <p><%= link_to "CONTINUE READING", news.link %></p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/participations/my_dashboard.html.erb
<%= render "shared/topnavbar" %>

<h1 id="title_dashboard">DASHBOARD</h1><hr>
<p class="p_dashboard"> Here you can view all the activities planned for the following days.</p>
<p class="p_dashboard"> Go to <i class="fa-solid fa-link fa-lg" style="color: #3b2747;"></i> to <strong>chat with other moms</strong> taking part in the activity.
And still possible to <strong>cancel the activity </strong>through <i class="fa-regular fa-rectangle-xmark fa-lg" style="color: #3b2747;"></i></p>
<div>
  <table class = "mytable">

    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Activity </th>
        <th scope="col">Category</th>
        <th scope="col">Price</th>
        <th scope="col">Location</th>
        <th scope="col">Attendee</th>
        <th scope="col">Date</th>
        <th scope="col">Chatroom</th>
        <th scope="col">Cancel</th>
      </tr>

  </thead>

  <tbody>
      <% start = 0 %>
    <% @participations.each do |participation| %>
      <tr>
      <td><%= start +=1 %></td>
        <td class="name"><%= link_to participation.activity.name, activity_path(participation.activity) %></td>
        <% if participation.activity.category == "indoor" %>
        <td class="color_indoor"><%= participation.activity.category %></td>
        <% else %>
        <td class="color_outdoor"><%= participation.activity.category %></td>
        <% end %>
        <td><%= participation.activity.price %>€</td>
        <td><%= participation.activity.location %></td>
        <td><%= participation.activity.participations.count %></td>
        <td><%= participation.participation_date %></td>
        <td><%= link_to chatroom_path(participation.activity.chatroom) do %>
          <i class="fa-solid fa-link fa-lg" style="color: #3b2747;"></i>
        <% end %>
        </td>
        <td><%= link_to participation_path(participation),  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} do %>
            <i class="fa-regular fa-rectangle-xmark fa-lg" style="color: #3b2747;"></i>
        <% end %></td>
        </tr>
    <% end %>
  </tbody>
  </table>
<div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <%= render "shared/topnavbar" %>
<% end %>
<div id="containernavbar">
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
    <div class="container-fluid d-block">
      <p class="titlenav" style="color:white; font-size: 50px; font-weight: 600; margin-left: 150px;">Nurturing New Mums Beyond Motherhood</p>
      <div class=" mainbuttons d-flex">
        <button class="discover"><%= link_to "DISCOVER ALL", activities_path %></button>
        <% if not user_signed_in? %>
        <button class="connect"><%= link_to "CONNECT", new_user_session_path %></button>
        <% else %>
        <button class="news"><%= link_to "TIPS & TRICKS",  news_index_path %></button>
        <% end %>
      </div>
      <div class="cities" >
        <%= button_to "Antwerpen", "#toppage", params: {where: "Antwerpen"}, method: :get, class: "btn text-white" %>
        <%= button_to "Brussels", "#toppage", params: {where: "Brussels"}, method: :get, class: "btn btn-primary" %>
        <%= button_to "Wallonia", "#toppage", params: {where: "Wallonia"}, method: :get, class: "btn btn-primary" %>
        <%= button_to "Gent", "#toppage", params: {where: "Gent"}, method: :get, class: "btn btn-primary" %>
      </div>
    </div>
      <%= image_tag "new.png", class: "img" %>
  </div>
</div>

app/views/shared/_search.html.erb
<div style="height: 20px"> </div>

<div>
  <%= simple_form_for :search, url: root_path, method: :get do |f| %>
    <div class="search-form-control form-group">
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword"
        %>
      <button name="button" type="submit" class="btn btn-flat">
        <i class="fas fa-search"></i> Search
      </button>
    </div>
  <% end %>
</div>

app/views/shared/_topnavbar.html.erb
<div id="globalcontainer" data-controller="button">
  <div class="navbar navbar-expand-sm navbar-light navbarr-lewagon" id="topnavbar">
    <div class="container-fluid" style="background-color: #472151">
      <div>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <%= link_to activities_path(), class: "navbar-brand" do %>
        <%= image_tag "new.png", class: "logotop", style: "width: 130px;"%>
        <% end %>
              <div class="sidemenu">
        <li class="nav-item">
          <a class="nav-link" href="/my_dashboard"><i class="fa-solid fa-table-columns" style="color: white;"></i>MY DASHBOARD</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/news"><i class="fa-solid fa-dice-six" style="color: white;"></i>TIPS & TRICKS</a>
        </li>
      </ul>
      </div>

      <div class="d-flex" data-controller="slidemenu">

        <div class="d-flex" style="text-align: center;" class="d-none" data-slidemenu-target="items">
          <ul style="display: flex; align-items: center;">
            <li style="margin-right: 10px;"><%= link_to destroy_user_session_path, data: {turbo_method: "delete"} do %>
            <i class="fa-solid fa-power-off fa-xl" style="color: #ffffff;"></i>
            <% end %></li>
            <li class="edit" style="margin-right: 10px;"><%= link_to edit_user_registration_path, data: { turbo_action: "replace" } do %>
            <i class="fa-regular fa-pen-to-square fa-xl" style="color: #ffffff;"></i>
            <% end %></li>
          </ul>
        </div>

        <div >
          <% if user_signed_in? && current_user.avatar.key %>
            <a style="background: none;" data-action="click -> slidemenu#slide"><%= cl_image_tag current_user.avatar.key, class: "avatar-bordered"%></a>
          <% else %>
            <%= image_tag "avatar.png", class: "avatar-large" %>
          <% end %>
        </div>
        </ul>
      </div>
    </div>
  </div>
</div>